apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nsqetmxi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nsqetmxi:84ee8ffa01694b026a35d9ddc78313177cd17699@sha256:0d9c4be139c62a2d13f0d0194c86d231766b2e90273d4ad332081f6e29c8dcfa
          name: container-image
